project:
  type: website
  resources:
  - /./www/
  - /./listings/
  output-dir: docs
  render:
    - "*.qmd"
    - "!/./catalogue-env/"
execute:
  freeze: auto
website:
  title: "AI Nexus"
  favicon: /./favicon.ico
  site-url: "https://ministryofjustice.github.io/rd-service-catalogue/"
  search: true
  open-graph: true
  navbar:
    style: floating
    title: "AI Nexus Homepage"
    left:
      - icon: rss
        href: index.xml
format:
  html:
    theme: 
      light: cosmo
      dark: sandstone
    toc: false
