name: Test Package
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-24.04 # pin to avoid breaking changes when runner images update latest
    timeout-minutes: 15
    strategy:
      fail-fast: false # ensures entire python version matrix executes to completion
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12"]
    steps:
    - name: Checkout code
      uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0
    - name: Set up Python
      uses: actions/setup-python@f677139bbe7f9c59b41e40162b753c062f5d49a3 # v5.2.0
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install '.[dev]'

    - name: pre-commit
      uses: actions/cache@2cdf405574d6ef1f33a1d12acccd3ae82f47b3f2 # sha for v4.1.0
      with:
        path: ~/.cache/pre-commit/
        key: pre-commit-4|${{ env.pythonLocation }}|${{ hashFiles('.pre-commit-config.yaml') }}
    - run: |
        pre-commit install
        pre-commit autoupdate --repo https://github.com/pre-commit/pre-commit-hooks
        pre-commit run --show-diff-on-failure --color=always --all-files
    - name: Run Tests and Generate Coverage Report
      env:
        PY_COLORS: 1
      run: |
        coverage run -m pytest
        coverage xml
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@b9fd7d16f6d7d1b5d2bec1a2887e65ceed900238 #v4.6.0
      with:
        file: ./coverage.xml
        flags: unittests
        verbose: true
        token: ${{secrets.CODECOV_TOKEN}}
